[global]
# Development settings
showErrorDetails = true

[server]
# Server configuration
address = "localhost"
headless = false
runOnSave = true
enableCORS = false
enableXsrfProtection = false
# fileWatcherType = "poll"

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501


[theme]
base="dark"
primaryColor="#26bad4"


# Additional CSS for better theme switching
[client]
# Enable theme switching
showErrorDetails = true
